//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBuNan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string comId { get; set; }
        public string comContent { get; set; }
        public string userId { get; set; }
        public System.DateTime comCretate { get; set; }
    
        public virtual User User { get; set; }
    }
}
