//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBuNan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public string finId { get; set; }
        public int finScore { get; set; }
        public string userId { get; set; }
        public string fin_pushUser { get; set; }
        public int finStatus { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
