//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBuNan.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITBuNanEntities : DbContext
    {
        public ITBuNanEntities()
            : base("name=ITBuNanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Finance> Finance { get; set; }
        public virtual DbSet<Recommend> Recommend { get; set; }
        public virtual DbSet<Res_Category> Res_Category { get; set; }
        public virtual DbSet<ResourceMsg> ResourceMsg { get; set; }

        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserCollection> UserCollection { get; set; }
        public virtual DbSet<UserCollectionType> UserCollectionType { get; set; }
        public virtual DbSet<UserMessage> UserMessage { get; set; }
    }
}
