//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBuNan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommend
    {
        public string recId { get; set; }
        public string resId { get; set; }
        public System.DateTime recTime { get; set; }
    
        public virtual ResourceMsg ResourceMsg { get; set; }
    }
}
