//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBuNan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Res_Category()
        {
            this.ResourceMsg = new HashSet<ResourceMsg>();
        }
    
        public string resCategoryId { get; set; }
        public string resCategoryName { get; set; }
        public System.DateTime resCategoryCreate { get; set; }
        public int resCategoryStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceMsg> ResourceMsg { get; set; }
    }
}
