//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBuNan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCollection
    {
        public string ColID { get; set; }
        public string resID { get; set; }
        public string ColTime { get; set; }
        public string userColTypeID { get; set; }
        public string userID { get; set; }
    
        public virtual ResourceMsg ResourceMsg { get; set; }
        public virtual User User { get; set; }
        public virtual UserCollectionType UserCollectionType { get; set; }
    }
}
