//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBuNan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public string msgID { get; set; }
        public string userIDSend { get; set; }
        public string userIDReceive { get; set; }
        public string msgContent { get; set; }
        public int msgType { get; set; }
        public System.DateTime msgCreate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
