//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITBuNan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Comment = new HashSet<Comment>();
            this.Finance = new HashSet<Finance>();
            this.Finance1 = new HashSet<Finance>();
            this.ResourceMsg = new HashSet<ResourceMsg>();
            this.UserCollection = new HashSet<UserCollection>();
            this.UserCollectionType = new HashSet<UserCollectionType>();
            this.UserMessage = new HashSet<UserMessage>();
            this.UserMessage1 = new HashSet<UserMessage>();
        }
    
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserLoginAccount { get; set; }
        public string UserLoginPwd { get; set; }
        public string UserTel { get; set; }
        public string UserEmail { get; set; }
        public System.DateTime UserCreateTime { get; set; }
        public string UserIcon { get; set; }
        public string UserToken { get; set; }
        public System.DateTime UserTokenExpire { get; set; }
        public string UserPush { get; set; }
        public int UserStatus { get; set; }
        public int UserType { get; set; }
        public string UserRemark { get; set; }
        public int UserIntegration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Finance> Finance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Finance> Finance1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceMsg> ResourceMsg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCollection> UserCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCollectionType> UserCollectionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMessage> UserMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMessage> UserMessage1 { get; set; }
    }
}
